-- Core/ClassData.lua
-- Default spell lists per class, preloaded on PLAYER_LOGIN

local JFCT = JalleFCT

JFCT.ClassData = {
    WARRIOR = {
        { id = 163201, name = "Execute" },
        { id = 23881,  name = "Bloodthirst" },
        { id = 1464,   name = "Slam" },
        { id = 12294,  name = "Mortal Strike" },
        { id = 845,    name = "Cleave" },
        { id = 6572,   name = "Revenge" },
        { id = 20243,  name = "Devastate" },
        { id = 7384,   name = "Overpower" },
        { id = 46924,  name = "Bladestorm" },
        { id = 167105, name = "Colossus Smash" },
        { id = 262161, name = "Warbreaker" },
        { id = 184367, name = "Rampage" },
        { id = 202168, name = "Impending Victory" },
        { id = 6343,   name = "Thunder Clap" },
    },
    PALADIN = {
        { id = 35395,  name = "Crusader Strike" },
        { id = 53595,  name = "Hammer of the Righteous" },
        { id = 24275,  name = "Hammer of Wrath" },
        { id = 85256,  name = "Templar's Verdict" },
        { id = 53385,  name = "Divine Storm" },
        { id = 20271,  name = "Judgment" },
        { id = 82326,  name = "Holy Light" },
        { id = 19750,  name = "Flash of Light" },
        { id = 96172,  name = "Hand of Light" },
        { id = 184575, name = "Blade of Justice" },
        { id = 343527, name = "Shield of Vengeance" },
    },
    HUNTER = {
        { id = 19434,  name = "Aimed Shot" },
        { id = 185358, name = "Arcane Shot" },
        { id = 2643,   name = "Multi-Shot" },
        { id = 257044, name = "Rapid Fire" },
        { id = 190925, name = "Mongoose Bite" },
        { id = 259387, name = "Kill Shot" },
        { id = 56641,  name = "Steady Shot" },
        { id = 193455, name = "Cobra Shot" },
        { id = 212436, name = "Butchery" },
    },
    ROGUE = {
        { id = 8676,   name = "Ambush" },
        { id = 2098,   name = "Eviscerate" },
        { id = 1329,   name = "Mutilate" },
        { id = 193315, name = "Sinister Strike" },
        { id = 315496, name = "Flagellation" },
        { id = 196819, name = "Blade Flurry" },
        { id = 121411, name = "Crimson Tempest" },
        { id = 5374,   name = "Mutilate" },
        { id = 280719, name = "Secret Technique" },
    },
    PRIEST = {
        { id = 15407,  name = "Mind Flay" },
        { id = 8092,   name = "Mind Blast" },
        { id = 32379,  name = "Shadow Word: Death" },
        { id = 34914,  name = "Vampiric Touch" },
        { id = 589,    name = "Shadow Word: Pain" },
        { id = 194249, name = "Devouring Plague" },
        { id = 2061,   name = "Flash Heal" },
        { id = 2060,   name = "Greater Heal" },
        { id = 596,    name = "Prayer of Healing" },
        { id = 228260, name = "Void Eruption" },
    },
    SHAMAN = {
        { id = 17364,  name = "Stormstrike" },
        { id = 25504,  name = "Windfury Attack" },
        { id = 188196, name = "Lightning Bolt" },
        { id = 421,    name = "Chain Lightning" },
        { id = 51505,  name = "Lava Burst" },
        { id = 8042,   name = "Earth Shock" },
        { id = 188443, name = "Chain Harvest" },
        { id = 1064,   name = "Chain Heal" },
        { id = 61882,  name = "Earthquake" },
    },
    MAGE = {
        { id = 133,    name = "Fireball" },
        { id = 11366,  name = "Pyroblast" },
        { id = 2136,   name = "Fire Blast" },
        { id = 116,    name = "Frostbolt" },
        { id = 84714,  name = "Frozen Orb" },
        { id = 30451,  name = "Arcane Blast" },
        { id = 44425,  name = "Arcane Barrage" },
        { id = 190356, name = "Blizzard" },
        { id = 257537, name = "Ice Lance" },
    },
    WARLOCK = {
        { id = 686,    name = "Shadow Bolt" },
        { id = 17877,  name = "Shadowburn" },
        { id = 29722,  name = "Incinerate" },
        { id = 348,    name = "Immolate" },
        { id = 980,    name = "Agony" },
        { id = 172,    name = "Corruption" },
        { id = 48181,  name = "Haunt" },
        { id = 196447, name = "Channel Demonfire" },
        { id = 264178, name = "Demonbolt" },
    },
    MONK = {
        { id = 107428, name = "Rising Sun Kick" },
        { id = 101546, name = "Spinning Crane Kick" },
        { id = 115181, name = "Breath of Fire" },
        { id = 117952, name = "Crackling Jade Lightning" },
        { id = 148187, name = "Rushing Jade Wind" },
        { id = 100784, name = "Blackout Kick" },
        { id = 115315, name = "Summon Black Ox Statue" },
        { id = 124682, name = "Enveloping Mist" },
    },
    DRUID = {
        { id = 5176,   name = "Wrath" },
        { id = 8921,   name = "Moonfire" },
        { id = 93402,  name = "Sunfire" },
        { id = 78674,  name = "Starsurge" },
        { id = 22568,  name = "Ferocious Bite" },
        { id = 1079,   name = "Rip" },
        { id = 5221,   name = "Shred" },
        { id = 33876,  name = "Mangle" },
        { id = 194153, name = "Starfire" },
        { id = 202347, name = "Stellar Flare" },
    },
    DEMONHUNTER = {
        { id = 188499, name = "Blade Dance" },
        { id = 185123, name = "Throw Glaive" },
        { id = 228477, name = "Soul Cleave" },
        { id = 179057, name = "Chaos Strike" },
        { id = 197125, name = "Death Sweep" },
        { id = 211881, name = "Fel Eruption" },
        { id = 258860, name = "Immolation Aura" },
        { id = 162794, name = "Elysian Decree" },
    },
    DEATHKNIGHT = {
        { id = 49998,  name = "Death Strike" },
        { id = 43265,  name = "Death and Decay" },
        { id = 47541,  name = "Death Coil" },
        { id = 55090,  name = "Scourge Strike" },
        { id = 49020,  name = "Obliterate" },
        { id = 49143,  name = "Frost Strike" },
        { id = 55095,  name = "Howling Blast" },
        { id = 207311, name = "Clawing Shadows" },
    },
    EVOKER = {
        { id = 357208, name = "Fire Breath" },
        { id = 357210, name = "Eternity Surge" },
        { id = 361500, name = "Living Flame" },
        { id = 362969, name = "Azure Strike" },
        { id = 375087, name = "Disintegrate" },
        { id = 382266, name = "Shattering Star" },
        { id = 359073, name = "Empowered Breath" },
    },
}

function JFCT.ClassData.PreloadClass(class)
    local spells = JFCT.ClassData[class]
    if not spells then return end
    for _, spell in ipairs(spells) do
        JFCT.Config.RegisterSpell(spell.id, spell.name)
    end
end
